"""Production Estimator — Analyzes build_spec.yaml and estimates cost/duration.

Reads a build_spec.yaml (generated by roadbook_to_spec.py), cross-references with
agent_registry.json and model_router.py cost tiers, then outputs a detailed JSON
estimate for the production phase.

Usage:
    python -m factory.integration.production_estimator \
        --spec projects/growmeldai/specs/build_spec.yaml \
        --format json
"""

import argparse
import json
import logging
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

try:
    import yaml
    _HAS_YAML = True
except ImportError:
    yaml = None
    _HAS_YAML = False

FACTORY_BASE = Path(__file__).resolve().parents[2]

# ── Cost per API call by model tier (USD) ─────────────────────────────────
# Based on config/model_router.py tier system
MODEL_COST = {
    "haiku": 0.001,
    "sonnet": 0.01,
    "opus": 0.05,
    "deterministic": 0.0,
    "thebrain": 0.012,   # TheBrain routes mostly to sonnet, slight overhead
    "sonnet-4-6": 0.012,
    "gemini-flash": 0.002,
}

# ── Production phases with expected agent calls ───────────────────────────
PHASE_CONFIG = {
    "coding": {
        "agent_prefixes": ["CPL"],
        "calls_per_feature": 3,
        "description": "Code generation per feature",
    },
    "assembly": {
        "agent_prefixes": ["INF"],
        "calls_per_screen": 2,
        "description": "Screen assembly and integration",
    },
    "qa": {
        "agent_prefixes": ["QAF"],
        "calls_per_feature": 1,
        "description": "Quality assurance testing",
    },
    "store": {
        "agent_prefixes": ["STR", "STP", "SGN"],
        "calls_per_project": 4,
        "description": "Store preparation and submission",
    },
    "evolution": {
        "agent_prefixes": ["EVO"],
        "iterations": 5,
        "calls_per_iteration": 6,
        "description": "Post-launch evolution loop",
    },
}

# ── Complexity multipliers for duration ───────────────────────────────────
COMPLEXITY_HOURS = {"low": 0.5, "medium": 1.5, "high": 3.0}


def _normalize_model(raw: str) -> str:
    """Map default_model or model_tier to a MODEL_COST key."""
    if not raw:
        return "sonnet"
    r = raw.lower()
    if "haiku" in r:
        return "haiku"
    if "opus" in r:
        return "opus"
    if "sonnet-4-6" in r or "sonnet_4_6" in r:
        return "sonnet-4-6"
    if "sonnet" in r or r == "standard":
        return "sonnet"
    if "gemini" in r or "flash" in r:
        return "gemini-flash"
    if "thebrain" in r or "brain" in r:
        return "thebrain"
    if r in ("deterministic", "none"):
        return "deterministic"
    return "sonnet"


class ProductionEstimator:
    """Estimates cost and duration for a DriveAI Factory production run."""

    def __init__(self, spec_path: str, registry_path: str | None = None):
        self.spec_path = Path(spec_path)
        self.registry_path = Path(registry_path) if registry_path else (
            FACTORY_BASE / "factory" / "agent_registry.json"
        )
        self.spec = self._load_spec()
        self.agents = self._load_registry()

    def _load_spec(self) -> dict:
        text = self.spec_path.read_text(encoding="utf-8")
        if self.spec_path.suffix in (".yaml", ".yml"):
            if not _HAS_YAML:
                raise ImportError("PyYAML required for YAML specs: pip install pyyaml")
            return yaml.safe_load(text)
        return json.loads(text)

    def _load_registry(self) -> list[dict]:
        if not self.registry_path.exists():
            logger.warning("agent_registry.json not found at %s", self.registry_path)
            return []
        data = json.loads(self.registry_path.read_text(encoding="utf-8"))
        return data if isinstance(data, list) else data.get("agents", [])

    # ── Main estimate ─────────────────────────────────────────────────────

    def estimate(self) -> dict:
        scope = self._estimate_scope()
        platforms = self._check_platforms()
        phases = self._estimate_phases(scope)
        risks = self._identify_risks(scope, platforms)
        total_cost = sum(p["cost_usd"] for p in phases.values())
        total_calls = sum(p["api_calls"] for p in phases.values())

        return {
            "project": self.spec.get("project", {}),
            "scope": scope,
            "platforms": platforms,
            "phases": phases,
            "totals": {
                "cost_usd": round(total_cost, 2),
                "api_calls": total_calls,
                "estimated_hours": self._estimate_duration(scope),
                "target_cost_per_run": "$0.08 (current avg)",
            },
            "model_usage": self._model_usage_breakdown(),
            "risks": risks,
        }

    # ── Scope analysis ────────────────────────────────────────────────────

    def _estimate_scope(self) -> dict:
        features = self.spec.get("features", [])
        screens = self.spec.get("screens", [])
        assets = self.spec.get("assets", [])

        by_phase = {}
        by_priority = {}
        by_complexity = {}
        for f in features:
            ph = f.get("phase", "A")
            pr = f.get("priority", "unknown")
            cx = f.get("complexity", "medium")
            by_phase[ph] = by_phase.get(ph, 0) + 1
            by_priority[pr] = by_priority.get(pr, 0) + 1
            by_complexity[cx] = by_complexity.get(cx, 0) + 1

        launch_assets = sum(1 for a in assets if a.get("launch_critical"))

        return {
            "total_features": len(features),
            "total_screens": len(screens),
            "total_assets": len(assets),
            "launch_critical_assets": launch_assets,
            "features_by_phase": by_phase,
            "features_by_priority": by_priority,
            "features_by_complexity": by_complexity,
            "apis": len(self.spec.get("apis", [])),
        }

    # ── Platform readiness ────────────────────────────────────────────────

    def _check_platforms(self) -> dict:
        target = self.spec.get("target_lines", [])
        platforms = self.spec.get("platforms", {})

        # Map platform → required agent + assembly line
        line_agents = {
            "ios":     {"coder": "CPL-03", "assembler": "INF-06"},
            "android": {"coder": "CPL-20", "assembler": "INF-07"},
            "web":     {"coder": "CPL-22", "assembler": "INF-08"},
            "unity":   {"coder": None,     "assembler": "INF-09"},
        }

        agent_map = {a["id"]: a for a in self.agents if "id" in a}
        result = {}

        for line in target:
            agents_needed = line_agents.get(line, {})
            coder_id = agents_needed.get("coder")
            asm_id = agents_needed.get("assembler")

            coder = agent_map.get(coder_id, {})
            assembler = agent_map.get(asm_id, {})

            coder_ready = coder.get("status") == "active" if coder_id else False
            asm_ready = assembler.get("status") == "active"

            result[line] = {
                "ready": coder_ready and asm_ready,
                "coder": {
                    "id": coder_id,
                    "status": coder.get("status", "not_found"),
                    "model": coder.get("default_model", coder.get("model_tier", "unknown")),
                },
                "assembler": {
                    "id": asm_id,
                    "status": assembler.get("status", "not_found"),
                    "model": assembler.get("default_model", assembler.get("model_tier", "unknown")),
                },
                "tech_stack": platforms.get("tech_stack", {}).get(line, "unknown"),
            }

        return {"target_lines": target, "lines": result}

    # ── Phase cost estimates ──────────────────────────────────────────────

    def _estimate_phases(self, scope: dict) -> dict:
        n_features = scope["total_features"]
        n_screens = scope["total_screens"]
        agent_map = {a["id"]: a for a in self.agents if "id" in a}
        results = {}

        for phase_name, cfg in PHASE_CONFIG.items():
            # Find matching agents
            matching = [
                a for a in self.agents
                if any(a.get("id", "").startswith(p) for p in cfg["agent_prefixes"])
                and a.get("status") == "active"
            ]

            # Calculate API calls (per feature/screen, NOT multiplied by agent count)
            if "calls_per_feature" in cfg:
                calls = n_features * cfg["calls_per_feature"]
            elif "calls_per_screen" in cfg:
                calls = n_screens * cfg["calls_per_screen"]
            elif "calls_per_project" in cfg:
                calls = cfg["calls_per_project"]
            elif "calls_per_iteration" in cfg:
                calls = cfg["iterations"] * cfg["calls_per_iteration"]
            else:
                calls = 0

            # Calculate cost based on primary agent's model
            cost = 0.0
            if matching:
                model_raw = matching[0].get("default_model", matching[0].get("model_tier", "standard"))
                model_key = _normalize_model(model_raw)
                cost = calls * MODEL_COST.get(model_key, MODEL_COST["sonnet"])
            else:
                cost = calls * MODEL_COST["sonnet"]

            results[phase_name] = {
                "description": cfg["description"],
                "api_calls": calls,
                "cost_usd": round(cost, 2),
                "active_agents": [a["id"] for a in matching],
                "blocked": len(matching) == 0,
            }

        return results

    # ── Duration estimate ─────────────────────────────────────────────────

    def _estimate_duration(self, scope: dict) -> dict:
        features = self.spec.get("features", [])

        # Sum feature weeks from spec
        total_weeks = sum(f.get("weeks", 0) for f in features)

        # Estimate by complexity
        total_hours = 0.0
        for f in features:
            cx = f.get("complexity", "medium")
            total_hours += COMPLEXITY_HOURS.get(cx, 1.5)

        # Factory acceleration: ~10x faster than manual
        factory_hours = round(total_hours / 10, 1)

        return {
            "manual_weeks_estimated": total_weeks,
            "factory_hours_estimated": factory_hours,
            "factory_runs_estimated": max(1, round(factory_hours / 0.5)),
            "note": "Factory runs are ~30min each, parallelized across agents",
        }

    # ── Model usage breakdown ─────────────────────────────────────────────

    def _model_usage_breakdown(self) -> dict:
        counts = {}
        for a in self.agents:
            if a.get("status") != "active":
                continue
            raw = a.get("default_model", a.get("model_tier", "unknown"))
            model = _normalize_model(raw)
            counts[model] = counts.get(model, 0) + 1
        return {
            "active_agents_by_model": counts,
            "total_active": sum(counts.values()),
            "primary_model": max(counts, key=counts.get) if counts else "unknown",
        }

    # ── Risk identification ───────────────────────────────────────────────

    def _identify_risks(self, scope: dict, platforms: dict) -> list[dict]:
        risks = []

        # Check for disabled platforms in target
        for line, info in platforms.get("lines", {}).items():
            if not info["ready"]:
                reasons = []
                if info["coder"]["status"] != "active":
                    reasons.append(f"Coder {info['coder']['id']} is {info['coder']['status']}")
                if info["assembler"]["status"] != "active":
                    reasons.append(f"Assembler {info['assembler']['id']} is {info['assembler']['status']}")
                risks.append({
                    "level": "blocker",
                    "area": f"platform_{line}",
                    "message": f"Production line '{line}' not ready: {'; '.join(reasons)}",
                })

        # High complexity features
        high_cx = scope["features_by_complexity"].get("high", 0)
        if high_cx > 5:
            risks.append({
                "level": "warning",
                "area": "complexity",
                "message": f"{high_cx} high-complexity features — expect longer iteration cycles",
            })

        # Many APIs
        if scope["apis"] > 5:
            risks.append({
                "level": "info",
                "area": "integrations",
                "message": f"{scope['apis']} API integrations — each needs mock + test setup",
            })

        # Legal requirements
        legal = self.spec.get("legal", {})
        if legal.get("gdpr_consent_required") and legal.get("coppa_required"):
            risks.append({
                "level": "warning",
                "area": "legal",
                "message": "GDPR + COPPA compliance required — needs legal review agent",
            })

        # Feature count > 50
        if scope["total_features"] > 50:
            risks.append({
                "level": "info",
                "area": "scope",
                "message": f"{scope['total_features']} features — consider phased production (A first, B later)",
            })

        return risks


# ── CLI ───────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Estimate production cost and duration from build_spec.yaml"
    )
    parser.add_argument("--spec", required=True, help="Path to build_spec.yaml")
    parser.add_argument("--registry", default=None, help="Path to agent_registry.json (auto-detected)")
    parser.add_argument("--format", choices=["json", "summary"], default="json")
    args = parser.parse_args()

    estimator = ProductionEstimator(args.spec, args.registry)
    result = estimator.estimate()

    if args.format == "json":
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        _print_summary(result)


def _print_summary(est: dict):
    proj = est["project"]
    totals = est["totals"]
    print(f"\n{'='*60}")
    print(f"  Production Estimate: {proj.get('name', '?')}")
    print(f"{'='*60}")
    print(f"  Scope: {est['scope']['total_features']} features, "
          f"{est['scope']['total_screens']} screens, "
          f"{est['scope']['total_assets']} assets")
    print(f"  APIs:  {est['scope']['apis']}")
    print(f"\n  Cost:     ${totals['cost_usd']:.2f}")
    print(f"  Calls:    {totals['api_calls']}")
    print(f"  Duration: {totals['estimated_hours']['factory_hours_estimated']}h "
          f"({totals['estimated_hours']['factory_runs_estimated']} runs)")
    print(f"\n  Platforms:")
    for line, info in est["platforms"]["lines"].items():
        status = "READY" if info["ready"] else "BLOCKED"
        print(f"    {line}: {status} (coder={info['coder']['status']}, asm={info['assembler']['status']})")
    if est["risks"]:
        print(f"\n  Risks:")
        for r in est["risks"]:
            icon = {"blocker": "!!!", "warning": " ! ", "info": " i "}.get(r["level"], " ? ")
            print(f"    [{icon}] {r['message']}")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
