// Generated by DriveAI Motion Forge — Platform Adapter
// Animation: MI-018 (pulse)
// Duration: 0.3s, Ease: ease-out

using System.Collections;
using UnityEngine;

public class AnimMi018 : MonoBehaviour
{
    [Header("Animation Settings")]
    public float duration = 0.3f;
    public float delay = 0.0f;
    public bool playOnStart = true;

    private CanvasGroup _canvasGroup;
    private Vector3 _startPos;
    private Vector3 _startScale;

    void Awake()
    {
        _canvasGroup = GetComponent<CanvasGroup>();
        _startPos = transform.localPosition;
        _startScale = transform.localScale;
    }

    void Start()
    {
        if (playOnStart) Play();
    }

    public void Play()
    {
        StopAllCoroutines();
        StartCoroutine(Animate());
    }

    private float Ease(float t)
    {
        return t * (2f - t);
    }

    private IEnumerator Animate()
    {
        if (delay > 0f) yield return new WaitForSeconds(delay);

        {
            float elapsed = 0f;
            while (elapsed < duration)
            {
                elapsed += Time.deltaTime;
                float t = Mathf.Clamp01(elapsed / duration);
                float eased = Ease(t);

                float s = eased < 0.5f
                    ? Mathf.Lerp(1f, 1.15f, eased * 2f)
                    : Mathf.Lerp(1.15f, 1f, (eased - 0.5f) * 2f);
                transform.localScale = _startScale * s;

                yield return null;
            }

            // Snap to final values
            ApplyFinal();
        }
    }

    private void ApplyFinal()
    {
        transform.localScale = _startScale;
    }
}
