// Features/KIIdentifikation/Infrastructure/MLModels/TrafficSignMLModel.swift
import CoreML
import Vision
import Combine

struct MLPrediction {
    let labelId: String
    let confidence: Float
    let inferenceTimeMs: Int
}

// Placeholder for generated CoreML input/output classes
// (Generated by Xcode when converting .mlmodel to CoreML)

class TrafficSignRecognizerOutput: MLFeatureProvider {
    let classLabel: String
    let confidence: Double
    var featureNames: Set<String> { ["classLabel", "confidence"] }
    
    init(classLabel: String, confidence: Double) {
        self.classLabel = classLabel
        self.confidence = confidence
    }
    
    func featureValue(for featureName: String) -> MLFeatureValue? {
        if featureName == "classLabel" {
            return MLFeatureValue(string: classLabel)
        } else if featureName == "confidence" {
            return MLFeatureValue(double: confidence)
        }
        return nil
    }
}