"""Improvement Proposals — Factory self-improvement recommendations from monitoring signals."""

import streamlit as st
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from store_reader import StoreReader

st.set_page_config(page_title="Improvements — Factory Control Center", page_icon="🔧", layout="wide")

st.title("Improvement Proposals")
reader = StoreReader()

proposals = reader.improvements()
st.caption(f"{len(proposals)} improvement proposals")

if not proposals:
    st.info(
        "No improvement proposals yet. Proposals are generated by the Factory Improvement Analyzer "
        "when it detects patterns in watch events, compliance findings, accessibility reports, "
        "orchestration blockers, and agent memory."
    )
    st.stop()

# --- Filters ---
col1, col2, col3 = st.columns(3)

categories = sorted({p.get("category", "?") for p in proposals})
severities = sorted({p.get("severity", "?") for p in proposals})
statuses = sorted({p.get("status", "?") for p in proposals})

with col1:
    sel_category = st.selectbox("Category", ["all"] + categories)
with col2:
    sel_severity = st.selectbox("Severity", ["all"] + severities)
with col3:
    sel_status = st.selectbox("Status", ["all"] + statuses)

filtered = proposals
if sel_category != "all":
    filtered = [p for p in filtered if p.get("category") == sel_category]
if sel_severity != "all":
    filtered = [p for p in filtered if p.get("severity") == sel_severity]
if sel_status != "all":
    filtered = [p for p in filtered if p.get("status") == sel_status]

st.markdown("---")

# --- Summary Metrics ---
st.subheader("Overview")
active = [p for p in proposals if p.get("status") not in ("completed", "rejected", "deferred")]
sev_counts = {}
for p in active:
    s = p.get("severity", "info")
    sev_counts[s] = sev_counts.get(s, 0) + 1

cat_counts = {}
for p in active:
    c = p.get("category", "general")
    cat_counts[c] = cat_counts.get(c, 0) + 1

summary_cols = st.columns(5)
summary_cols[0].metric("Total", len(proposals))
summary_cols[1].metric("Active", len(active))
summary_cols[2].metric("Critical/High", sev_counts.get("critical", 0) + sev_counts.get("high", 0))
summary_cols[3].metric("New", sum(1 for p in proposals if p.get("status") == "new"))
summary_cols[4].metric("Completed", sum(1 for p in proposals if p.get("status") == "completed"))

# Category breakdown
if cat_counts:
    cat_cols = st.columns(min(len(cat_counts), 5))
    for i, (cat, count) in enumerate(sorted(cat_counts.items(), key=lambda x: -x[1])):
        cat_cols[i % len(cat_cols)].metric(cat.replace("_", " ").title(), count)

st.markdown("---")
st.caption(f"Showing {len(filtered)} of {len(proposals)} proposals")

# --- Proposal Cards ---
SEVERITY_ICONS = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢", "info": "⚪"}
STATUS_ICONS = {
    "new": "🆕", "evaluated": "🔍", "accepted": "✅", "in_progress": "⚡",
    "completed": "✔️", "rejected": "❌", "deferred": "⏸️",
}

for p in filtered:
    pid = p.get("proposal_id", "?")
    title = p.get("title", "Untitled")
    severity = p.get("severity", "?")
    status = p.get("status", "?")
    category = p.get("category", "?")
    sev_icon = SEVERITY_ICONS.get(severity, "⚪")
    status_icon = STATUS_ICONS.get(status, "")

    with st.expander(f"{sev_icon} {pid}: {title} — {category} [{status}]"):
        c1, c2, c3 = st.columns(3)
        c1.markdown(f"**Category**: `{category}`")
        c2.markdown(f"**Severity**: {sev_icon} `{severity}`")
        c3.markdown(f"**Status**: {status_icon} `{status}`")

        if p.get("summary"):
            st.markdown(f"**Summary**: {p['summary']}")

        if p.get("recommended_action"):
            st.markdown(f"**Recommended Action**: {p['recommended_action']}")

        if p.get("affected_systems"):
            st.markdown(f"**Affected Systems**: {', '.join(p['affected_systems'])}")

        if p.get("detected_from"):
            st.markdown(f"**Detected From**: `{p['detected_from']}`")

        if p.get("notes"):
            st.markdown(f"**Notes**: {p['notes']}")

        if p.get("created_at"):
            st.caption(f"Created: {p['created_at']}")
